### ISSUE TITLE
NL in documentation should be NR

### ISSUE THREAD

**Issue by holgerbrandl** [gvalkov/python-oneliner#3]
Currently examples with NL are broken.

Also in the initial example

        python -m oneliner -ne "%5d: %s" % (NR, _) < input

single quotes are missing around the python expression.

I'd be happy to help by sending a proper pull request but the project looks a bit dead to me. (which is is pitty because its looks great!)

**Comment by gvalkov** [comment]
Thanks for taking interest in this project. I fixed the examples and made some smalls changes to the [documentation](http://python-oneliner.readthedocs.org/en/latest/) and code, all while hoping to make it look a little less dead. Unfortunately, I haven't been able to spend much time on my open-source projects lately.

Any type of bug reports, suggestions and PRs would be appreciated.
